services:
  kros_car:
    image: wildbot_workspace:latest
    privileged: true
    device_cgroup_rules:
      - 'c 13:* rwm'
    env_file:
      - .env
    devices:
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/usb_wheel:/dev/usb_wheel"
      - "/dev/usb_robot_arm:/dev/usb_robot_arm"
    volumes:
      - ./configs:/configs:ro
      - /dev/input:/dev/input
      - /home/robot/桌面/wildbot_photos:/photos
      - /home/robot/wildbot_real car/wildbot_workspace-main:/workspaces
    networks:
      - my_bridge_network
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
                ros2 launch kros_car bringup.launch.py"

  joy_driver:
    image: wildbot_workspace:latest
    privileged: true
    env_file:
      - .env
    devices:
      - "/dev/input:/dev/input"
    networks:
      - my_bridge_network
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
                ros2 run joy joy_node --ros-args -p autorepeat_rate:=20.0"

  teleop_script:
    image: wildbot_workspace:latest
    volumes:
      - /home/robot/wildbot_real car/wildbot_workspace-main:/workspaces
    env_file:
      - .env
    networks:
      - my_bridge_network
    depends_on:
      - kros_car
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
                python3 /workspaces/joy_to_base_camera.py"

networks:
  my_bridge_network:
    driver: bridge